name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello
      run: echo "Hola Actions"
    - name: variable
      run: "${{ toJSON(github) }}"
  test:
    needs: build
    runs-on: ubuntu-22.04
    container:
      image: alexbh/moin:1.9.11-buster
    steps:
    - name: Print hello
      run: echo "Hola Actions"
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Testing environment
      run: |
        cat /etc/os-release
        python -V
        moin --version



