name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print hello
      run: echo "Hola Actions"
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file Dockerfile -t alexbh/moin:1.9.11-buster-updated .
