name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04
    container: alexbh/moin:1.9.11-buster
    steps:
    - name: Print hello
      run: echo "Hola Actions"
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Testing environment
      run: |
        cat /etc/os-release
        python -V
        moin --version



